<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-04T09:58:11 IST" name="Default suite" finished-at="2023-07-04T09:58:27 IST" duration-ms="16101">
    <groups>
    </groups>
    <test started-at="2023-07-04T09:58:11 IST" name="Default test" finished-at="2023-07-04T09:58:27 IST" duration-ms="16101">
      <class name="Runner_Script.HMS">
        <test-method is-config="true" signature="openAppln()[pri:0, instance:Runner_Script.HMS@2313052e]" started-at="2023-07-04T09:58:11 IST" name="openAppln" finished-at="2023-07-04T09:58:18 IST" duration-ms="6976" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openAppln -->
        <test-method signature="valid_login(java.lang.String,java.lang.String)[pri:0, instance:Runner_Script.HMS@2313052e]" started-at="2023-07-04T09:58:18 IST" name="valid_login" data-provider="testdata" finished-at="2023-07-04T09:58:20 IST" duration-ms="2743" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[dr.bro@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[dr.bro@1234]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at Runner_Script.HMS.valid_login(HMS.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- valid_login -->
        <test-method is-config="true" signature="closeAppln(org.testng.ITestResult)[pri:0, instance:Runner_Script.HMS@2313052e]" started-at="2023-07-04T09:58:20 IST" name="closeAppln" finished-at="2023-07-04T09:58:21 IST" duration-ms="688" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=valid_login status=FAILURE method=HMS.valid_login(java.lang.String,java.lang.String)[pri:0, instance:Runner_Script.HMS@2313052e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeAppln -->
        <test-method is-config="true" signature="openAppln()[pri:0, instance:Runner_Script.HMS@2313052e]" started-at="2023-07-04T09:58:21 IST" name="openAppln" finished-at="2023-07-04T09:58:24 IST" duration-ms="2506" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openAppln -->
        <test-method signature="valid_login(java.lang.String,java.lang.String)[pri:0, instance:Runner_Script.HMS@2313052e]" started-at="2023-07-04T09:58:24 IST" name="valid_login" data-provider="testdata" finished-at="2023-07-04T09:58:26 IST" duration-ms="2596" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[nimmi@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[nimmi@123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at Runner_Script.HMS.valid_login(HMS.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- valid_login -->
        <test-method is-config="true" signature="closeAppln(org.testng.ITestResult)[pri:0, instance:Runner_Script.HMS@2313052e]" started-at="2023-07-04T09:58:26 IST" name="closeAppln" finished-at="2023-07-04T09:58:27 IST" duration-ms="487" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=valid_login status=FAILURE method=HMS.valid_login(java.lang.String,java.lang.String)[pri:0, instance:Runner_Script.HMS@2313052e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeAppln -->
      </class> <!-- Runner_Script.HMS -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
